
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- CONTRIBUTING.md

github:
  host: clarkbw.github.io
  url: https://clarkbw.github.io/devtools-metrics

# metadata
title: 18F Digital Services Delivery
description: "18F builds effective, user-centric digital services focused on the interaction between government and the people and businesses it serves."
