
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- CONTRIBUTING.md

baseurl: /devtools-metrics

github:
  host: clarkbw.github.io
  page: /devtools-metrics
  url: https://clarkbw.github.io/devtools-metrics

# metadata
title: DevTools Metrics Dashboard
description: A Metrics Dashboard for Firefox DevTools collected using our anonymous Telemetry service.
twitter:
  site: "@FirefoxDevTools"
  creator: "@clarkbw"
